require('core.plugin_config.colorscheme')
require('core.plugin_config.lualine')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.indent')
require('core.plugin_config.neotree')
require('core.plugin_config.neogit')
require('core.plugin_config.nvim-comment')